#!/bin/sh

NAME=dockerd
DAEMON=/opt/usr/bin/$NAME
PIDFILE=/opt/var/run/$NAME.pid
DAEMON_ARGS="--bridge=none --iptables=false"
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

insmod /usr/lib/modules/aufs.ko
insmod /usr/lib/modules/macvlan.ko
sudo ip link set eth0 promisc on

/opt/usr/bin/dockerd $DAEMON_ARGS &
